worker_processes auto;
events {
        worker_connections 1024;
}
http {
        include mime.types;
default_type application/octet-stream;
sendfile on;
keepalive_timeout 65;
server_tokens off;
gzip on;
client_max_body_size 100m;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
upstream ylotc {
        server 172.17.0.80:8888 max_fails=1 fail_timeout=3;
        server 172.17.0.81:8888 backup;
}
upstream client_app {
    ip_hash;
        server 172.17.0.80:8886 ;
        server 172.17.0.81:8886 ;

}

server {
listen   8082;
server_name localhost;

access_log  /var/log/nginx/access.log;
error_log   /var/log/nginx/error.log;

proxy_buffers 16 64k;
proxy_buffer_size 128k;
root /usr/local/nginx/html/client;

location / {
                index index.html index.htm;
                try_files $uri $uri/ /index.html;
                if ($request_filename ~* .*\.(htm|html)$)
                {
                add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
                }
                }

location ~ ^/trs_hub_api/  {
        add_header 'Access-Control-Allow-Origin' 'http://127.0.0.1:80';
        rewrite ^/trs_hub_api/(.*) /$1 break;
        proxy_pass http://client_app/$1$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        proxy_read_timeout 36000s;
        }

location ~ ^/java/
                {
                rewrite ^/java/(.*) /$1 break;
                proxy_pass http://client_app/$1$is_args$args;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 36000s;
        }
location ~ ^/open/
                {
                proxy_pass http://client_app;
                proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        proxy_read_timeout 36000s;
        }

        error_page 404 /404.html;
                    location = /404.html
                        {
                    root /usr/local/nginx/html/;
                    }

}


server {
listen   8081;
server_name localhost;
proxy_buffers 16 64k;
proxy_buffer_size 128k;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_read_timeout 36000s;

location ~ ^/trs_hub_api/
                {
                    rewrite ^/trs_hub_api/(.*) /$1 break;
                    proxy_pass http://hedge_app/$1$is_args$args;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_read_timeout 36000s;
        }

location /otcdms-ui
                {
                    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
                    add_header Pragma "no-cache";
                    add_header Expires 0;
                    alias /usr/local/nginx/html/otcdms-ui;
                    index index.html index.htm;
                    try_files $uri $uri/ /otcdms-ui/index.html;

                }

location ~ ^/java/
                {
                    rewrite ^/java/(.*) /$1 break;
                    proxy_pass http://hedge_app/$1$is_args$args;
                    proxy_read_timeout 36000s;
}
location /
                 {
                     proxy_pass http://ylotc;
                     proxy_read_timeout 36000s;
                 }

        }
}