! Configuration File for keepalived

global_defs {
    router_id LVS_BACKUP
}

# ----------------- Nginx 高可用配置 -----------------
vrrp_script chk_nginx {
    script "/usr/local/keepalive/etc/keepalived/check_nginx.sh"
    interval 2
    weight -20
    fall 2
    rise 1
}

vrrp_instance VI_NGINX {
    state BACKUP
    interface eth1  # 内部网络接口
    virtual_router_id 88
    priority 90
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass 1111nginx
    }

    virtual_ipaddress {
        192.168.2.100/24 dev eth0  # VIP绑定在外部接口
    }

    track_script {
        chk_nginx
    }

    unicast_src_ip 172.17.0.81
    unicast_peer {
        172.17.0.80
    }
}

# ----------------- MySQL 高可用配置 -----------------
vrrp_script chk_mysql {
    script "/usr/local/keepalive/etc/keepalived/check_mysql.sh"
    interval 2
    weight -20
    fall 2
    rise 1
}

vrrp_instance VI_MYSQL {
    state BACKUP
    interface eth1  # 内部网络接口
    virtual_router_id 86
    priority 90
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass 2222mysql
    }

    virtual_ipaddress {
        172.17.0.100/16 dev eth1  # VIP绑定在外部接口
    }

    track_script {
        chk_mysql
    }

    unicast_src_ip 172.17.0.81
    unicast_peer {
        172.17.0.80
    }
}