apiVersion: v1
kind: ConfigMap
metadata:
  name: market-config
  labels:
    app: market
    chart: trs
    release: "{{ .Release.Name }}"
data:
  application-dev.yml: |
    spring:
      datasource:
        url: jdbc:mysql://{{ .Values.db.mysql.host }}:{{ .Values.db.mysql.port }}/yltrs_ylcms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&allowMultiQueries=true
        username: {{ .Values.db.mysql.username | quote }}
        password: {{ .Values.db.mysql.password | quote }}
        driver-class-name: com.mysql.cj.jdbc.Driver
      kafka:
        bootstrap-servers: {{ .Values.kafka.bootstrapServers | quote }}
        producer: # 生产者
          retries: 3 # 设置大于0的值，则客户端会将发送失败的记录重新发送
          batch-size: 0
          buffer-memory: 33554432
          acks: all
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer

  application.yml: |
    #服务配置
    server:
      port: 20000
    one-marketdata:
      acc: {{ .Values.oneMarketdata.acc }}
      pwd: {{ .Values.oneMarketdata.pwd }}
      mac: {{ .Values.oneMarketdata.mac }}
      # 订阅渠道
      topics: {{ .Values.oneMarketdata.topics }}
      #是否支持重启恢复（刷新一遍当前订阅code的实时行情）,默认true
      autoRecovery: {{ .Values.oneMarketdata.autoRecovery }}
      # 服务端ip
      ip: {{ .Values.oneMarketdata.ip }}
      # 服务端port
      port: {{ .Values.oneMarketdata.port }}
      # 本地缓存配置
      cache:
        # 是否启用缓存
        enable: true
        # 缓存数据过期时间，单位小
        expiredHoursAfterWrite: 8
        # 缓存初始化空间大小，对象数
        initSize: 4000
        # 缓存最大控件大小，对象数
        maxSize: 10000
    logging:
      level:
        root: info
    spring:
      # 默认使用本地环境配置
      profiles:
        active: dev
      application:
        name: market
    mybatis-plus:
      mapper-locations: classpath*:/mapper/**/*.xml
      type-aliases-package: com.yieldchain.market.entity
      configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      global-config:
        db-config:
          id-type: auto
          logic-delete-field: deleted
          logic-delete-value: 1
          logic-not-delete-value: 0
    management:
      endpoints:
        web:
          exposure:
            include: health,prometheus
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
        prometheus:
          enabled: true
      metrics:
        tags:
          application: ${spring.application.name}